version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "truong2911"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend-net

  backend:
    build: ./backend
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=lego_store;encrypt=false
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: truong2911
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-net

  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge